codecov:
  notify:
    require_ci_to_pass: no
  version: 2

coverage:
  precision: 2
  round: down
  range: 0...100
  status:
    project:
      default:
        target: auto  # Automatically sets the target coverage based on previous results
        threshold: 1% # Allows a 1% drop in coverage
        if_no_uploads: success  # Mark as success if no uploads
    patch:
      default:
        target: auto
        threshold: 1%
        if_no_uploads: success

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: no
  branches:
    - main
    - develop

flags:
  backend:
    paths:
      - "src/backend/*"
  frontend:
    paths:
      - "src/frontend/*"

ignore:
  - "tests/*"
  - "docs/*"
  - "**/*.md"
  - "**/*.yml"
  - "**/*.yaml"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

fixes:
  - "*"
  - "*/**"
  - "**/*"

yaml:
  branch: develop

browsers:
  - name: Chrome
    bin: "/usr/bin/chromium-browser"
    args:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --disable-software-rasterizer
      - --headless
  - name: Firefox
    bin: "/usr/bin/firefox"
    args:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --disable-software-rasterizer
      - --headless
